# Generated by Django 5.1.5 on 2026-02-18 04:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='URLAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=2048)),
                ('last_scan_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('warning', 'Warning'), ('error', 'Error')], default='pending', max_length=20)),
                ('last_scan_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='url_assets', to='accounts.organization')),
            ],
            options={
                'verbose_name': 'URL Asset',
                'verbose_name_plural': 'URL Assets',
                'ordering': ['-created_at'],
                'unique_together': {('organization', 'url')},
            },
        ),
    ]
