# Generated by Django 6.0 on 2026-07-15 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urls_manager', '0005_add_ownership_verification_method_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlasset',
            name='name',
            field=models.CharField(blank=True, default='', help_text='Optional user-facing label (e.g. "Sitio principal"). Falls back to the URL when empty.', max_length=120),
        ),
    ]
