# Generated by Django 6.0 on 2026-07-15 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urls_manager', '0006_urlasset_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='urlasset',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'URL Asset', 'verbose_name_plural': 'URL Assets'},
        ),
    ]
