# Generated by Django 5.1.5 on 2026-03-27 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="accepted_terms_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="organization",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "Pro"), ("ultimate", "Ultimate")],
                default="free",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="url_limit",
            field=models.IntegerField(default=1),
        ),
    ]
