# Generated by Django 5.1.5 on 2026-05-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_invitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="stripe_customer_id",
            field=models.CharField(
                blank=True, help_text="Stripe Customer ID", max_length=120, null=True
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="stripe_subscription_id",
            field=models.CharField(
                blank=True,
                help_text="Stripe Subscription ID",
                max_length=120,
                null=True,
            ),
        ),
    ]
