# Generated by Django 6.0 on 2026-07-15 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_organization_stripe_customer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('org_admin', 'Org Admin'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
