# Generated by Django 5.1.5 on 2026-06-01 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_organization_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationLLMConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("default", "Default (Gemini)"),
                            ("opencode_go", "OpenCode Go"),
                            ("openai", "OpenAI"),
                            ("anthropic", "Anthropic"),
                            ("gemini", "Google Gemini"),
                        ],
                        default="default",
                        max_length=20,
                    ),
                ),
                ("api_key", models.CharField(blank=True, max_length=512)),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="llm_config",
                        to="accounts.organization",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
            },
        ),
    ]
