# Generated by Django 6.0 on 2026-07-15 20:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='expires_at',
            field=models.DateTimeField(default=accounts.models._default_invitation_expiry),
        ),
    ]
