# Generated by Django 5.1.5 on 2026-07-18 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_organizationllmconfig'),
        ('accounts', '0006_invitation_expires_at'),
    ]

    operations = [
    ]
