# Generated by Django 5.1.5 on 2026-05-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("scheduled", "Scheduled Report"),
                    ("alert", "High Severity Alert"),
                    ("manual", "Manual Report"),
                ],
                max_length=20,
            ),
        ),
    ]
