# Generated by Django 6.0 on 2026-07-15 21:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('role_change', 'Role Change'), ('org_change', 'Organization Change'), ('plan_change', 'Plan Change')], max_length=20)),
                ('performed_by_email', models.CharField(blank=True, default='', max_length=255)),
                ('target_user_id', models.IntegerField(blank=True, null=True)),
                ('target_user_email', models.CharField(blank=True, default='', max_length=255)),
                ('target_org_id', models.IntegerField(blank=True, null=True)),
                ('target_org_name', models.CharField(blank=True, default='', max_length=255)),
                ('before_value', models.CharField(blank=True, default='', max_length=255)),
                ('after_value', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Action Log',
                'verbose_name_plural': 'Admin Action Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
