# Generated by Django 6.0 on 2026-07-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit_log', '0002_adminactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminactionlog',
            name='action',
            field=models.CharField(choices=[('role_change', 'Role Change'), ('org_change', 'Organization Change'), ('plan_change', 'Plan Change'), ('block_change', 'Block/Unblock')], max_length=20),
        ),
    ]
