# Generated by Django 5.1.5 on 2026-02-18 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('urls_manager', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('error', 'Error')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('engine_version', models.CharField(default='1.0.0', max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scans', to=settings.AUTH_USER_MODEL)),
                ('url_asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='urls_manager.urlasset')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('severity', models.CharField(choices=[('HIGH', 'Alto'), ('MEDIUM', 'Medio'), ('LOW', 'Bajo'), ('INFO', 'Informativo')], max_length=10)),
                ('category', models.CharField(choices=[('headers', 'HTTP Headers'), ('ssl', 'SSL/TLS'), ('cookies', 'Cookies'), ('info_disclosure', 'Information Disclosure'), ('dns', 'DNS Configuration'), ('mixed_content', 'Mixed Content'), ('redirect', 'Open Redirect'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField()),
                ('recommendation', models.TextField(blank=True, default='')),
                ('evidence', models.TextField(blank=True, default='')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='scanner.scan')),
            ],
            options={
                'ordering': [models.Case(models.When(severity='HIGH', then=0), models.When(severity='MEDIUM', then=1), models.When(severity='LOW', then=2), models.When(severity='INFO', then=3), default=4, output_field=models.IntegerField())],
            },
        ),
    ]
