# Generated by Django 5.1.5 on 2026-02-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="finding",
            options={
                "ordering": [
                    models.Case(
                        models.When(severity="CRITICAL", then=0),
                        models.When(severity="HIGH", then=1),
                        models.When(severity="MEDIUM", then=2),
                        models.When(severity="LOW", then=3),
                        models.When(severity="INFO", then=4),
                        default=5,
                        output_field=models.IntegerField(),
                    )
                ]
            },
        ),
        migrations.AlterField(
            model_name="finding",
            name="category",
            field=models.CharField(
                choices=[
                    ("headers", "HTTP Headers"),
                    ("ssl", "SSL/TLS"),
                    ("cookies", "Cookies"),
                    ("info_disclosure", "Information Disclosure"),
                    ("dns", "DNS Configuration"),
                    ("mixed_content", "Mixed Content"),
                    ("redirect", "Open Redirect"),
                    ("sqli", "SQL Injection"),
                    ("xss", "Cross-Site Scripting"),
                    ("nosqli", "NoSQL Injection"),
                    ("cmd_injection", "OS Command Injection"),
                    ("xxe", "XXE Injection"),
                    ("ssti", "Server-Side Template Injection"),
                    ("csrf", "CSRF"),
                    ("clickjacking", "Clickjacking"),
                    ("cors", "CORS Misconfiguration"),
                    ("ssrf", "SSRF"),
                    ("path_traversal", "Path Traversal"),
                    ("access_control", "Broken Access Control"),
                    ("bypass_403", "403 Bypass"),
                    ("host_header", "HTTP Host Header"),
                    ("auth", "Authentication"),
                    ("jwt", "JWT Vulnerabilities"),
                    ("oauth", "OAuth"),
                    ("websockets", "WebSockets"),
                    ("http_smuggling", "HTTP Request Smuggling"),
                    ("cache_poisoning", "Web Cache Poisoning"),
                    ("deserialization", "Insecure Deserialization"),
                    ("file_upload", "File Upload Vulnerabilities"),
                    ("prototype_pollution", "Prototype Pollution"),
                    ("graphql", "GraphQL"),
                    ("race_condition", "Race Conditions"),
                    ("api", "API Security"),
                    ("subdomain_takeover", "Subdomain Takeover"),
                    ("cache_deception", "Web Cache Deception"),
                    ("llm", "Web LLM Attacks"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="finding",
            name="severity",
            field=models.CharField(
                choices=[
                    ("CRITICAL", "Crítico"),
                    ("HIGH", "Alto"),
                    ("MEDIUM", "Medio"),
                    ("LOW", "Bajo"),
                    ("INFO", "Informativo"),
                ],
                max_length=10,
            ),
        ),
    ]
