# Generated by Django 5.1.5 on 2026-02-25 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanner", "0002_alter_finding_options_alter_finding_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finding",
            name="category",
            field=models.CharField(
                choices=[
                    ("headers", "HTTP Headers"),
                    ("ssl", "SSL/TLS"),
                    ("cookies", "Cookies"),
                    ("info_disclosure", "Information Disclosure"),
                    ("dns", "DNS Configuration"),
                    ("mixed_content", "Mixed Content"),
                    ("redirect", "Open Redirect"),
                    ("sqli", "SQL Injection"),
                    ("xss", "Cross-Site Scripting"),
                    ("nosqli", "NoSQL Injection"),
                    ("cmd_injection", "OS Command Injection"),
                    ("xxe", "XXE Injection"),
                    ("ssti", "Server-Side Template Injection"),
                    ("csrf", "CSRF"),
                    ("clickjacking", "Clickjacking"),
                    ("cors", "CORS Misconfiguration"),
                    ("ssrf", "SSRF"),
                    ("path_traversal", "Path Traversal"),
                    ("access_control", "Broken Access Control"),
                    ("bypass_403", "403 Bypass"),
                    ("host_header", "HTTP Host Header"),
                    ("auth", "Authentication"),
                    ("jwt", "JWT Vulnerabilities"),
                    ("oauth", "OAuth"),
                    ("websockets", "WebSockets"),
                    ("http_smuggling", "HTTP Request Smuggling"),
                    ("cache_poisoning", "Web Cache Poisoning"),
                    ("deserialization", "Insecure Deserialization"),
                    ("file_upload", "File Upload Vulnerabilities"),
                    ("prototype_pollution", "Prototype Pollution"),
                    ("graphql", "GraphQL"),
                    ("race_condition", "Race Conditions"),
                    ("api", "API Security"),
                    ("subdomain_takeover", "Subdomain Takeover"),
                    ("subdomain", "Subdomain Discovery"),
                    ("cache_deception", "Web Cache Deception"),
                    ("llm", "Web LLM Attacks"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
