"""Views for reports app."""
import os
from io import BytesIO

from django.http import HttpResponse
from django.db.models import Q
from rest_framework import permissions, status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.response import Response
from openpyxl import Workbook
from openpyxl.utils import get_column_letter
from openpyxl.styles import Font, Alignment, PatternFill, Border, Side
from openpyxl.drawing.image import Image as XlImage

# ReportLab is optional — only needed for PDF generation
try:
    from reportlab.lib import colors as rl_colors
    from reportlab.lib.pagesizes import LETTER
    from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
    from reportlab.lib.units import inch
    from reportlab.platypus import (
        Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle, Image as RLImage,
    )

    REPORTLAB_AVAILABLE = True
except ImportError:
    REPORTLAB_AVAILABLE = False

from scanner.models import Scan
from urls_manager.models import URLAsset
from .models import ExecutiveSummary
from .serializers import ExecutiveSummarySerializer


# Absolute path to the Vigia brand logo (generated by reports/logo_gen.py)
LOGO_PATH = os.path.join(os.path.dirname(__file__), "static", "logo_vigia.png")
LOGO_AVAILABLE = os.path.exists(LOGO_PATH)


def _logo_flowable(width=180):
    """Return a ReportLab Image flowable for the logo, or None if missing."""
    if not LOGO_AVAILABLE or not REPORTLAB_AVAILABLE:
        return None
    try:
        img = RLImage(LOGO_PATH, width=width, height=width * (120 / 420))
        img.hAlign = "LEFT"
        return img
    except Exception:
        return None


BRAND_FILL = PatternFill(start_color='FF1E293B', end_color='FF1E293B', fill_type='solid')
BRAND_TITLE_FONT = Font(bold=True, size=13, color='FFFFFFFF')
BRAND_SUBTITLE_FONT = Font(size=9, italic=True, color='FF64748B')
ZEBRA_FILL = PatternFill(start_color='FFF8FAFC', end_color='FFF8FAFC', fill_type='solid')


def _setup_sheet_header(ws, title, subtitle=None, col_span=2, logo_scale=0.22):
    """Insert the brand logo + a title banner row at the top of a sheet.

    Row 1 is reserved for the logo image (tall, no cell values so it never
    collides with the table below it — that's what caused the logo to sit
    on top of the data before). Row 2 is a colored title banner, row 3 an
    optional subtitle. Callers keep using ws.append() afterwards; openpyxl
    resumes at the next free row automatically since rows 2-3 already have
    cell values.
    """
    if LOGO_AVAILABLE:
        try:
            img = XlImage(LOGO_PATH)
            img.width = int(img.width * logo_scale)
            img.height = int(img.height * logo_scale)
            ws.add_image(img, "A1")
        except Exception:
            pass
    ws.row_dimensions[1].height = 34

    last_col = get_column_letter(max(col_span, 1))
    ws.merge_cells(f'A2:{last_col}2')
    title_cell = ws.cell(row=2, column=1, value=title)
    title_cell.font = BRAND_TITLE_FONT
    title_cell.alignment = Alignment(horizontal='left', vertical='center', indent=1)
    for col in range(1, col_span + 1):
        ws.cell(row=2, column=col).fill = BRAND_FILL
    ws.row_dimensions[2].height = 22

    ws.merge_cells(f'A3:{last_col}3')
    sub_cell = ws.cell(row=3, column=1, value=subtitle or '')
    sub_cell.font = BRAND_SUBTITLE_FONT
    sub_cell.alignment = Alignment(horizontal='left', vertical='center', indent=1)
    ws.row_dimensions[3].height = 16


def _finalize_table_sheet(ws, header_row, tab_color=None, zebra=True):
    """Freeze panes below the header, add autofilter, tab color, zebra rows."""
    if tab_color:
        ws.sheet_properties.tabColor = tab_color
    last_col = get_column_letter(ws.max_column)
    last_row = ws.max_row
    ws.freeze_panes = f'A{header_row + 1}'
    if last_row >= header_row:
        ws.auto_filter.ref = f'A{header_row}:{last_col}{last_row}'
    if zebra:
        for row_idx in range(header_row + 1, last_row + 1):
            if (row_idx - header_row) % 2 == 0:
                for cell in ws[row_idx]:
                    if cell.fill.start_color.rgb in (None, '00000000'):
                        cell.fill = ZEBRA_FILL


def _build_pdf_with_reportlab(scan, findings, summary_content):
    """Build a styled PDF using ReportLab (cross-platform, always available)."""
    def _clean(text):
        return (str(text or '')).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')

    def _severity_color(severity):
        mapping = {
            'CRITICAL': rl_colors.HexColor('#7c3aed'),
            'HIGH': rl_colors.HexColor('#dc2626'),
            'MEDIUM': rl_colors.HexColor('#d97706'),
            'LOW': rl_colors.HexColor('#2563eb'),
            'INFO': rl_colors.HexColor('#475569'),
        }
        return mapping.get((severity or '').upper(), rl_colors.HexColor('#334155'))

    findings_list = list(findings)

    stats = {
        'total': len(findings_list),
        'critical': sum(1 for f in findings_list if f.severity == 'CRITICAL'),
        'high': sum(1 for f in findings_list if f.severity == 'HIGH'),
        'medium': sum(1 for f in findings_list if f.severity == 'MEDIUM'),
        'low': sum(1 for f in findings_list if f.severity == 'LOW'),
    }

    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=0.5 * inch,
        rightMargin=0.5 * inch,
        topMargin=0.5 * inch,
        bottomMargin=0.5 * inch,
        title=f'Reporte Scan {scan.pk}',
    )

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'VigiaTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=20,
        textColor=rl_colors.white,
        leading=24,
        spaceAfter=4,
    )
    subtitle_style = ParagraphStyle(
        'VigiaSubTitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        textColor=rl_colors.HexColor('#bfdbfe'),
        leading=12,
    )
    section_title_style = ParagraphStyle(
        'SectionTitle',
        parent=styles['Heading3'],
        fontName='Helvetica-Bold',
        fontSize=11,
        textColor=rl_colors.HexColor('#0f172a'),
        spaceBefore=12,
        spaceAfter=6,
    )
    body_style = ParagraphStyle(
        'BodyCopy',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=8,
        leading=11,
        textColor=rl_colors.HexColor('#1f2937'),
    )
    header_finding_style = ParagraphStyle(
        'FindingHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        textColor=rl_colors.white,
        leading=11,
    )
    thin_border = rl_colors.HexColor('#cbd5e1')

    story = []

    logo = _logo_flowable(width=160)
    if logo is not None:
        story.append(logo)
        story.append(Spacer(1, 6))

    header_table = Table(
        [[
            Paragraph('Reporte de Auditoria Web', title_style),
            Paragraph('VIGIA', subtitle_style),
        ]],
        colWidths=[5.6 * inch, 1.0 * inch],
    )
    header_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), rl_colors.HexColor('#1d4ed8')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('ALIGN', (1, 0), (1, 0), 'RIGHT'),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(header_table)

    scan_date = scan.started_at.strftime('%d/%m/%Y %H:%M') if scan.started_at else '-'
    metadata = [
        [Paragraph('<b>Scan ID</b>', body_style), Paragraph(_clean(scan.pk), body_style)],
        [Paragraph('<b>URL</b>', body_style), Paragraph(_clean(scan.url_asset.url if scan.url_asset else '-'), body_style)],
        [Paragraph('<b>Estado</b>', body_style), Paragraph(_clean(scan.status), body_style)],
        [Paragraph('<b>Fecha</b>', body_style), Paragraph(scan_date, body_style)],
    ]
    meta_table = Table(metadata, colWidths=[1.0 * inch, 5.6 * inch])
    meta_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), rl_colors.HexColor('#eff6ff')),
        ('GRID', (0, 0), (-1, -1), 0.4, rl_colors.HexColor('#cbd5e1')),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 8),
        ('RIGHTPADDING', (0, 0), (-1, -1), 8),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    story.append(meta_table)
    story.append(Spacer(1, 10))

    story.append(Paragraph('Resumen de Hallazgos', section_title_style))
    stat_row = [[
        Paragraph('<b>Total</b><br/><font size="14">{}</font>'.format(stats['total']), body_style),
        Paragraph('<b>Critico</b><br/><font size="14">{}</font>'.format(stats['critical']), body_style),
        Paragraph('<b>Alto</b><br/><font size="14">{}</font>'.format(stats['high']), body_style),
        Paragraph('<b>Medio</b><br/><font size="14">{}</font>'.format(stats['medium']), body_style),
        Paragraph('<b>Bajo</b><br/><font size="14">{}</font>'.format(stats['low']), body_style),
    ]]
    stats_table = Table(stat_row, colWidths=[1.3 * inch] * 5)
    stats_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (0, 0), rl_colors.HexColor('#e2e8f0')),
        ('BACKGROUND', (1, 0), (1, 0), rl_colors.HexColor('#ede9fe')),
        ('BACKGROUND', (2, 0), (2, 0), rl_colors.HexColor('#fee2e2')),
        ('BACKGROUND', (3, 0), (3, 0), rl_colors.HexColor('#fef3c7')),
        ('BACKGROUND', (4, 0), (4, 0), rl_colors.HexColor('#dbeafe')),
        ('BOX', (0, 0), (-1, -1), 0.5, rl_colors.HexColor('#94a3b8')),
        ('INNERGRID', (0, 0), (-1, -1), 0.5, rl_colors.HexColor('#cbd5e1')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(stats_table)
    story.append(Spacer(1, 12))

    if summary_content:
        story.append(Paragraph('Resumen Ejecutivo', section_title_style))
        summary_text = _clean(summary_content)
        if len(summary_text) > 4000:
            summary_text = summary_text[:4000] + '...'
        for part in summary_text.split('\n'):
            part = part.strip()
            if not part:
                continue
            story.append(Paragraph(part, body_style))
            story.append(Spacer(1, 3))
        story.append(Spacer(1, 8))

    story.append(Paragraph('Hallazgos Tecnicos', section_title_style))
    # Table: Severity | Title | Category | Description | Recommendation | Evidence
    findings_header = [
        Paragraph('<b>Sev.</b>', header_finding_style),
        Paragraph('<b>Titulo</b>', header_finding_style),
        Paragraph('<b>Categoria</b>', header_finding_style),
        Paragraph('<b>Descripcion</b>', header_finding_style),
        Paragraph('<b>Recomendacion</b>', header_finding_style),
        Paragraph('<b>Evidencia</b>', header_finding_style),
    ]
    findings_data = [findings_header]

    for finding in findings_list:
        findings_data.append([
            Paragraph(_clean(finding.severity or '-'), body_style),
            Paragraph(_clean(finding.title or '-'), body_style),
            Paragraph(_clean(finding.category or '-'), body_style),
            Paragraph(_clean(finding.description or '-'), body_style),
            Paragraph(_clean(finding.recommendation or '-'), body_style),
            Paragraph(_clean(finding.evidence or '-'), body_style),
        ])

    if len(findings_data) == 1:
        findings_data.append([
            Paragraph('INFO', body_style),
            Paragraph('Sin hallazgos detectados', body_style),
            Paragraph('-', body_style),
            Paragraph('No se encontraron vulnerabilidades en este escaneo.', body_style),
            Paragraph('Mantener monitoreo continuo.', body_style),
            Paragraph('-', body_style),
        ])

    col_widths = [0.55 * inch, 1.4 * inch, 0.8 * inch, 1.4 * inch, 1.4 * inch, 1.1 * inch]
    findings_table = Table(findings_data, colWidths=col_widths, repeatRows=1)
    table_style_cmds = [
        ('BACKGROUND', (0, 0), (-1, 0), rl_colors.HexColor('#1e293b')),
        ('TEXTCOLOR', (0, 0), (-1, 0), rl_colors.white),
        ('GRID', (0, 0), (-1, -1), 0.3, thin_border),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('LEFTPADDING', (0, 0), (-1, -1), 4),
        ('RIGHTPADDING', (0, 0), (-1, -1), 4),
        ('TOPPADDING', (0, 0), (-1, -1), 4),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
    ]
    for row_idx, finding in enumerate(findings_list, start=1):
        stripe = rl_colors.HexColor('#f8fafc') if row_idx % 2 else rl_colors.white
        table_style_cmds.append(('BACKGROUND', (1, row_idx), (-1, row_idx), stripe))
        table_style_cmds.append(('BACKGROUND', (0, row_idx), (0, row_idx), _severity_color(finding.severity)))
        table_style_cmds.append(('TEXTCOLOR', (0, row_idx), (0, row_idx), rl_colors.white))

    findings_table.setStyle(TableStyle(table_style_cmds))
    story.append(findings_table)
    story.append(Spacer(1, 10))
    story.append(Paragraph('Generado por Vigia', ParagraphStyle(
        'Footer',
        parent=styles['Normal'],
        alignment=1,
        fontSize=8,
        textColor=rl_colors.HexColor('#64748b'),
    )))

    doc.build(story)
    buffer.seek(0)
    return buffer.getvalue()


def _build_report_file_response(scan, fmt):
    """Return a file response for report download in requested format."""
    findings = scan.findings.all()

    summary_content = ''
    try:
        summary_content = scan.executive_summary.content
    except ExecutiveSummary.DoesNotExist:
        pass

    html_content = f"""<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Reporte de Auditoría - {scan.url_asset.url}</title>
    <style>
        body {{ font-family: 'Segoe UI', Arial, sans-serif; margin: 40px; color: #1a1a2e; }}
        h1 {{ color: #16213e; border-bottom: 3px solid #0f3460; padding-bottom: 10px; }}
        h2 {{ color: #0f3460; margin-top: 30px; }}
        .meta {{ background: #f0f4f8; padding: 15px; border-radius: 8px; margin: 20px 0; }}
        .stats {{ display: flex; gap: 20px; margin: 20px 0; }}
        .stat {{ padding: 15px 25px; border-radius: 8px; text-align: center; color: white; }}
        .stat.critical {{ background: #8b5cf6; }}
        .stat.high {{ background: #e74c3c; }}
        .stat.medium {{ background: #f39c12; }}
        .stat.low {{ background: #3498db; }}
        .finding {{ border: 1px solid #ddd; border-radius: 8px; padding: 15px; margin: 10px 0; border-left: 4px solid; }}
        .finding.CRITICAL {{ border-left-color: #8b5cf6; }}
        .finding.HIGH {{ border-left-color: #e74c3c; }}
        .finding.MEDIUM {{ border-left-color: #f39c12; }}
        .finding.LOW {{ border-left-color: #3498db; }}
        .finding.INFO {{ border-left-color: #95a5a6; }}
        .severity {{ display: inline-block; padding: 2px 8px; border-radius: 4px; color: white; font-size: 12px; }}
        .severity.CRITICAL {{ background: #8b5cf6; }}
        .severity.HIGH {{ background: #e74c3c; }}
        .severity.MEDIUM {{ background: #f39c12; }}
        .severity.LOW {{ background: #3498db; }}
        .severity.INFO {{ background: #95a5a6; }}
        .executive {{ background: #f8f9fa; padding: 20px; border-radius: 8px; border-left: 4px solid #0f3460; }}
        @media print {{ body {{ margin: 20px; }} }}
    </style>
</head>
<body>
    <h1>🔒 Reporte de Auditoría Web</h1>
    <div class="meta">
        <strong>URL:</strong> {scan.url_asset.url}<br>
        <strong>Fecha:</strong> {scan.started_at.strftime('%d/%m/%Y %H:%M')}<br>
        <strong>Estado:</strong> {scan.status}
    </div>

    <h2>📊 Resumen de Hallazgos</h2>
    <div class="stats">
        <div class="stat critical">Crítico: {findings.filter(severity='CRITICAL').count()}</div>
        <div class="stat high">Alto: {findings.filter(severity='HIGH').count()}</div>
        <div class="stat medium">Medio: {findings.filter(severity='MEDIUM').count()}</div>
        <div class="stat low">Bajo: {findings.filter(severity='LOW').count()}</div>
    </div>

    {"<h2>📋 Resumen Ejecutivo</h2><div class='executive'>" + summary_content + "</div>" if summary_content else ""}

    <h2>🔍 Hallazgos Técnicos</h2>
    {"".join([f'''
    <div class="finding {f.severity}">
        <h3><span class="severity {f.severity}">{f.severity}</span> {f.title}</h3>
        <p><strong>Categoría:</strong> {f.category}</p>
        <p>{f.description}</p>
        <p><strong>Recomendación:</strong> {f.recommendation}</p>
        {"<p><strong>Evidencia:</strong> " + f.evidence + "</p>" if f.evidence else ""}
    </div>''' for f in findings])}

    <hr>
    <p style="text-align:center; color:#999;">Generado por Auditoría Web Automatizada para PYMES</p>
</body>
</html>"""

    if fmt in ('excel', 'xlsx'):
        workbook = Workbook()

        # --- Styles ---
        header_font = Font(bold=True, size=11, color='FFFFFF')
        header_fill = PatternFill(start_color='1E293B', end_color='1E293B', fill_type='solid')
        header_align = Alignment(horizontal='center', vertical='center', wrap_text=True)
        cell_align = Alignment(vertical='top', wrap_text=True)
        thin_border = Border(
            left=Side(style='thin', color='CBD5E1'),
            right=Side(style='thin', color='CBD5E1'),
            top=Side(style='thin', color='CBD5E1'),
            bottom=Side(style='thin', color='CBD5E1'),
        )
        url_font = Font(color='2563EB', underline='single')

        def style_header(ws, row_num, col_count):
            for col in range(1, col_count + 1):
                cell = ws.cell(row=row_num, column=col)
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = header_align
                cell.border = thin_border

        def style_data_cell(cell):
            cell.alignment = cell_align
            cell.border = thin_border

        def auto_width(ws, min_width=10, max_width=55):
            for col_cells in ws.columns:
                col_letter = get_column_letter(col_cells[0].column)
                max_len = 0
                for cell in col_cells:
                    val = str(cell.value or '')
                    max_len = max(max_len, min(len(val), max_width))
                ws.column_dimensions[col_letter].width = max(max_len + 2, min_width)

        scan_date_str = scan.started_at.strftime('%d/%m/%Y %H:%M') if scan.started_at else '-'
        scan_url = scan.url_asset.url if scan.url_asset else '-'

        # --- Hoja 1: Resumen ---
        summary_ws = workbook.active
        summary_ws.title = 'Resumen'
        _setup_sheet_header(summary_ws, 'Reporte de Auditoria', scan_url, col_span=2)
        summary_header_row = summary_ws.max_row + 1
        summary_ws.append(['Campo', 'Valor'])
        style_header(summary_ws, summary_header_row, 2)

        summary_rows = [
            ['Scan ID', scan.pk],
            ['URL', scan_url],
            ['Estado', scan.status],
            ['Fecha inicio', scan_date_str],
            ['Fecha fin', scan.finished_at.strftime('%d/%m/%Y %H:%M') if scan.finished_at else '-'],
            ['Total hallazgos', findings.count()],
            ['Criticos', findings.filter(severity='CRITICAL').count()],
            ['Altos', findings.filter(severity='HIGH').count()],
            ['Medios', findings.filter(severity='MEDIUM').count()],
            ['Bajos', findings.filter(severity='LOW').count()],
            ['Info', findings.filter(severity='INFO').count()],
        ]
        for row in summary_rows:
            summary_ws.append(row)
            current_row = summary_ws.max_row
            for cell in summary_ws[current_row]:
                style_data_cell(cell)
            if row[0] == 'URL':
                summary_ws.cell(row=current_row, column=2).font = url_font
        auto_width(summary_ws)
        _finalize_table_sheet(summary_ws, summary_header_row, tab_color='2563EB', zebra=True)

        # --- Hoja 2: Hallazgos (con detalle completo) ---
        findings_ws = workbook.create_sheet(title='Hallazgos')
        findings_headers = [
            'ID', 'URL', 'Fecha Escaneo', 'Titulo', 'Severidad',
            'Categoria', 'Descripcion', 'Recomendacion', 'Evidencia',
        ]
        _setup_sheet_header(findings_ws, 'Hallazgos Tecnicos', scan_url, col_span=len(findings_headers))
        findings_header_row = findings_ws.max_row + 1
        findings_ws.append(findings_headers)
        style_header(findings_ws, findings_header_row, len(findings_headers))

        severity_fills = {
            'CRITICAL': PatternFill(start_color='FFEDE9FE', end_color='FFEDE9FE', fill_type='solid'),
            'HIGH': PatternFill(start_color='FFFEE2E2', end_color='FFFEE2E2', fill_type='solid'),
            'MEDIUM': PatternFill(start_color='FFFEF3C7', end_color='FFFEF3C7', fill_type='solid'),
            'LOW': PatternFill(start_color='FFDBEAFE', end_color='FFDBEAFE', fill_type='solid'),
        }

        for finding in findings:
            row_data = [
                finding.pk,
                scan_url,
                scan_date_str,
                finding.title or '',
                finding.severity or '',
                finding.category or '',
                finding.description or '',
                finding.recommendation or '',
                finding.evidence or '',
            ]
            findings_ws.append(row_data)
            for cell in findings_ws[findings_ws.max_row]:
                style_data_cell(cell)
            sev_fill = severity_fills.get((finding.severity or '').upper())
            if sev_fill:
                findings_ws.cell(row=findings_ws.max_row, column=5).fill = sev_fill

        auto_width(findings_ws)
        _finalize_table_sheet(findings_ws, findings_header_row, tab_color='DC2626', zebra=False)

        # --- Hoja 3: Resumen Ejecutivo (si existe) ---
        if summary_content:
            executive_ws = workbook.create_sheet(title='Resumen Ejecutivo')
            _setup_sheet_header(executive_ws, 'Resumen Ejecutivo (IA)', scan_url, col_span=2)
            exec_header_row = executive_ws.max_row + 1
            executive_ws.append(['Contenido del Resumen Ejecutivo'])
            executive_ws.merge_cells(start_row=exec_header_row, start_column=1, end_row=exec_header_row, end_column=2)
            style_header(executive_ws, exec_header_row, 1)
            executive_ws.append([summary_content])
            content_row = executive_ws.max_row
            executive_ws.merge_cells(start_row=content_row, start_column=1, end_row=content_row, end_column=2)
            cell = executive_ws.cell(row=content_row, column=1)
            cell.alignment = Alignment(vertical='top', wrap_text=True)
            executive_ws.column_dimensions['A'].width = 80
            executive_ws.sheet_properties.tabColor = '7C3AED'

        output = BytesIO()
        workbook.save(output)
        output.seek(0)

        response = HttpResponse(
            output.getvalue(),
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        response['Content-Disposition'] = f'attachment; filename="reporte_scan_{scan.pk}.xlsx"'
        return response

    if fmt == 'pdf':
        # Try WeasyPrint first (produces nicer PDF with CSS), fall back to ReportLab
        weasyprint_error = None
        try:
            from weasyprint import HTML

            pdf = HTML(string=html_content).write_pdf()
            response = HttpResponse(pdf, content_type='application/pdf')
            response['Content-Disposition'] = f'attachment; filename="reporte_scan_{scan.pk}.pdf"'
            return response
        except Exception as exc:
            weasyprint_error = str(exc)

        if REPORTLAB_AVAILABLE:
            try:
                pdf = _build_pdf_with_reportlab(scan, findings, summary_content)
                response = HttpResponse(pdf, content_type='application/pdf')
                response['Content-Disposition'] = f'attachment; filename="reporte_scan_{scan.pk}.pdf"'
                return response
            except Exception as fallback_exc:
                return Response(
                    {
                        'detail': f'No se pudo generar el PDF. WeasyPrint: {weasyprint_error}. ReportLab: {fallback_exc}',
                    },
                    status=status.HTTP_500_INTERNAL_SERVER_ERROR,
                )
        else:
            return Response(
                {
                    'detail': (
                        'No se pudo generar el PDF. Instala WeasyPrint o ReportLab en el servidor. '
                        f'WeasyPrint error: {weasyprint_error}. ReportLab no esta instalado.'
                    ),
                },
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

    return Response(
        {'detail': 'Formato no soportado. Usa format=excel o format=pdf.'},
        status=status.HTTP_400_BAD_REQUEST,
    )


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def report_detail(request, scan_id):
    """Get full report (technical + executive) for a scan."""
    access_filter = Q(url_asset__organization_id=request.user.organization_id)
    access_filter |= Q(created_by=request.user)

    try:
        scan = Scan.objects.select_related(
            'url_asset', 'url_asset__organization'
        ).prefetch_related('findings').filter(
            access_filter,
        ).get(
            pk=scan_id,
        )
    except Scan.DoesNotExist:
        if Scan.objects.filter(pk=scan_id).exists():
            return Response(
                {'detail': 'No tienes permiso para ver este reporte.'},
                status=status.HTTP_403_FORBIDDEN,
            )
        return Response({'detail': 'Scan not found.'}, status=404)

    # Get executive summary if available
    summary = None
    try:
        summary = ExecutiveSummarySerializer(scan.executive_summary).data
    except ExecutiveSummary.DoesNotExist:
        pass

    findings = scan.findings.all()

    download_flag = (request.query_params.get('download') or '').lower()
    fmt = (request.query_params.get('format') or '').lower()
    if download_flag in {'1', 'true', 'yes'} and fmt:
        return _build_report_file_response(scan, fmt)

    report_data = {
        'scan_id': scan.pk,
        'url': scan.url_asset.url,
        'scan_status': scan.status,
        'scan_date': scan.started_at,
        'finished_at': scan.finished_at,
        'findings': [
            {
                'id': f.pk,
                'title': f.title,
                'severity': f.severity,
                'category': f.category,
                'description': f.description,
                'recommendation': f.recommendation,
                'evidence': f.evidence,
            }
            for f in findings
        ],
        'executive_summary': summary,
        'stats': {
            'total': findings.count(),
            'critical': findings.filter(severity='CRITICAL').count(),
            'high': findings.filter(severity='HIGH').count(),
            'medium': findings.filter(severity='MEDIUM').count(),
            'low': findings.filter(severity='LOW').count(),
            'info': findings.filter(severity='INFO').count(),
        },
    }

    return Response(report_data)


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def download_report(request, scan_id):
    """Download report as Excel (.xlsx) or PDF."""
    access_filter = Q(url_asset__organization_id=request.user.organization_id)
    access_filter |= Q(created_by=request.user)

    try:
        scan = Scan.objects.select_related(
            'url_asset', 'url_asset__organization'
        ).prefetch_related('findings').filter(
            access_filter,
        ).get(
            pk=scan_id,
        )
    except Scan.DoesNotExist:
        if Scan.objects.filter(pk=scan_id).exists():
            return Response(
                {'detail': 'No tienes permiso para descargar este reporte.'},
                status=status.HTTP_403_FORBIDDEN,
            )
        return Response({'detail': 'Scan not found.'}, status=404)

    fmt = (request.query_params.get('format', 'excel') or 'excel').lower()
    return _build_report_file_response(scan, fmt)


# ----------------------------------------------------------------------
# Organization-level date-range reports
# ----------------------------------------------------------------------

def _severity_color_rl(severity):
    if not REPORTLAB_AVAILABLE:
        return None
    mapping = {
        'CRITICAL': rl_colors.HexColor('#7c3aed'),
        'HIGH': rl_colors.HexColor('#dc2626'),
        'MEDIUM': rl_colors.HexColor('#d97706'),
        'LOW': rl_colors.HexColor('#2563eb'),
        'INFO': rl_colors.HexColor('#475569'),
    }
    return mapping.get((severity or '').upper(), rl_colors.HexColor('#334155'))


def _clean_text(text):
    return (str(text or '')).replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')


def _aggregate_stats(findings_qs):
    findings = list(findings_qs)
    return {
        'total': len(findings),
        'critical': sum(1 for f in findings if f.severity == 'CRITICAL'),
        'high': sum(1 for f in findings if f.severity == 'HIGH'),
        'medium': sum(1 for f in findings if f.severity == 'MEDIUM'),
        'low': sum(1 for f in findings if f.severity == 'LOW'),
        'info': sum(1 for f in findings if f.severity == 'INFO'),
    }


def _build_org_pdf_reportlab(scans, org_name, start_str, end_str, scope_label=None):
    """Build an aggregate PDF for an organization's scans in a date range."""
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer, pagesize=LETTER,
        leftMargin=0.5 * inch, rightMargin=0.5 * inch,
        topMargin=0.5 * inch, bottomMargin=0.5 * inch,
        title=f'Reporte Organizacion {org_name}',
    )
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'OrgTitle', parent=styles['Heading1'],
        fontName='Helvetica-Bold', fontSize=18,
        textColor=rl_colors.HexColor('#0f172a'),
        leading=22, spaceAfter=6,
    )
    meta_style = ParagraphStyle(
        'OrgMeta', parent=styles['Normal'],
        fontName='Helvetica', fontSize=9,
        textColor=rl_colors.HexColor('#475569'), leading=12, spaceAfter=12,
    )
    section_style = ParagraphStyle(
        'OrgSection', parent=styles['Heading3'],
        fontName='Helvetica-Bold', fontSize=11,
        textColor=rl_colors.HexColor('#0f172a'),
        spaceBefore=10, spaceAfter=4,
    )
    scan_title_style = ParagraphStyle(
        'ScanTitle', parent=styles['Heading4'],
        fontName='Helvetica-Bold', fontSize=10,
        textColor=rl_colors.HexColor('#1e293b'),
        spaceBefore=8, spaceAfter=3,
    )
    body_style = ParagraphStyle(
        'OrgBody', parent=styles['Normal'],
        fontName='Helvetica', fontSize=8, leading=11,
        textColor=rl_colors.HexColor('#1f2937'),
    )

    story = []

    logo = _logo_flowable(width=180)
    if logo is not None:
        story.append(logo)
        story.append(Spacer(1, 8))

    story.append(Paragraph(_clean_text(f'Reporte de Auditoría - {org_name}'), title_style))
    story.append(Paragraph(
        _clean_text(
            f'Periodo: {start_str} a {end_str} · '
            f'Escaneos incluidos: {len(scans)}'
            + (f' · Sitio: {scope_label}' if scope_label else '')
        ),
        meta_style,
    ))

    # Aggregate stats
    all_findings = []
    for s in scans:
        all_findings.extend(s.findings.all())
    stats = {
        'total': len(all_findings),
        'critical': sum(1 for f in all_findings if f.severity == 'CRITICAL'),
        'high': sum(1 for f in all_findings if f.severity == 'HIGH'),
        'medium': sum(1 for f in all_findings if f.severity == 'MEDIUM'),
        'low': sum(1 for f in all_findings if f.severity == 'LOW'),
        'info': sum(1 for f in all_findings if f.severity == 'INFO'),
    }

    header_cell_style = ParagraphStyle(
        'OrgStatHeader', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=9,
        textColor=rl_colors.white, alignment=1,
    )
    stat_value_style = ParagraphStyle(
        'OrgStatValue', parent=styles['Normal'],
        fontName='Helvetica', fontSize=9,
        textColor=rl_colors.HexColor('#1f2937'), alignment=1,
    )
    finding_header_style = ParagraphStyle(
        'OrgFindingHeader', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=7,
        textColor=rl_colors.white,
    )
    finding_body_style = ParagraphStyle(
        'OrgFindingBody', parent=styles['Normal'],
        fontName='Helvetica', fontSize=7, leading=9,
        textColor=rl_colors.HexColor('#1f2937'),
    )
    finding_severity_style = ParagraphStyle(
        'OrgFindingSeverity', parent=styles['Normal'],
        fontName='Helvetica-Bold', fontSize=7, leading=9,
        textColor=rl_colors.white,
    )

    # Usable page width: LETTER (8.5in) minus 0.5in margins each side.
    page_width = 7.5 * inch

    story.append(Paragraph('Resumen de Hallazgos', section_style))
    stat_headers = ['Total', 'Críticos', 'Altos', 'Medios', 'Bajos', 'Info']
    stat_values = [stats['total'], stats['critical'], stats['high'],
                   stats['medium'], stats['low'], stats['info']]
    stats_data = [
        [Paragraph(h, header_cell_style) for h in stat_headers],
        [Paragraph(str(v), stat_value_style) for v in stat_values],
    ]
    stats_tbl = Table(stats_data, repeatRows=1, colWidths=[page_width / 6] * 6)
    stats_tbl.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), rl_colors.HexColor('#1e293b')),
        ('GRID', (0, 0), (-1, -1), 0.5, rl_colors.HexColor('#cbd5e1')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
    ]))
    story.append(stats_tbl)

    # Per-scan sections
    finding_col_widths = [0.7 * inch, 1.6 * inch, 1.1 * inch, page_width - 0.7 * inch - 1.6 * inch - 1.1 * inch]
    story.append(Paragraph('Detalle por Escaneo', section_style))
    for s in scans:
        findings = list(s.findings.all())
        url = s.url_asset.url if s.url_asset else 'N/A'
        story.append(Paragraph(
            _clean_text(
                f'Scan #{s.pk} · {url} · '
                f'{s.started_at.strftime("%Y-%m-%d %H:%M")} · '
                f'{s.status} · {len(findings)} hallazgos'
            ),
            scan_title_style,
        ))
        if not findings:
            story.append(Paragraph('Sin hallazgos en este escaneo.', body_style))
            continue
        rows = [[
            Paragraph('Severidad', finding_header_style),
            Paragraph('Titulo', finding_header_style),
            Paragraph('Categoria', finding_header_style),
            Paragraph('Descripcion', finding_header_style),
        ]]
        for f in findings:
            rows.append([
                Paragraph(_clean_text(f.severity), finding_severity_style),
                Paragraph(_clean_text(f.title), finding_body_style),
                Paragraph(_clean_text(f.category), finding_body_style),
                Paragraph(_clean_text(f.description), finding_body_style),
            ])
        tbl = Table(rows, repeatRows=1, colWidths=finding_col_widths)
        table_style_cmds = [
            ('BACKGROUND', (0, 0), (-1, 0), rl_colors.HexColor('#1e293b')),
            ('GRID', (0, 0), (-1, -1), 0.3, rl_colors.HexColor('#cbd5e1')),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 4),
            ('TOPPADDING', (0, 0), (-1, -1), 4),
        ]
        for row_idx, f in enumerate(findings, start=1):
            table_style_cmds.append(
                ('BACKGROUND', (0, row_idx), (0, row_idx), _severity_color_rl(f.severity))
            )
        tbl.setStyle(TableStyle(table_style_cmds))
        story.append(tbl)
        story.append(Spacer(1, 6))

    story.append(Paragraph(
        'Generado por Auditoría Web Automatizada para PYMES',
        body_style,
    ))
    doc.build(story)
    buffer.seek(0)
    return buffer


def _build_org_excel(scans, org_name, start_str, end_str, scope_label=None):
    """Build an aggregate Excel workbook for an organization's scans."""
    wb = Workbook()
    header_font = Font(name='Calibri', size=11, bold=True, color='FFFFFFFF')
    header_fill = PatternFill(
        start_color='FF1E293B', end_color='FF1E293B', fill_type='solid'
    )
    thin_side = Side(border_style='thin', color='FFCBD5E1')
    border = Border(left=thin_side, right=thin_side, top=thin_side, bottom=thin_side)
    cell_align = Alignment(wrap_text=True, vertical='top')

    period_sub = f'{org_name} · Periodo: {start_str} a {end_str}'
    if scope_label:
        period_sub += f' · Sitio: {scope_label}'

    def _auto_width(ws, border_=border, align_=cell_align, skip_rows=0):
        for col in ws.columns:
            max_len = 0
            for cell in col:
                if cell.row <= skip_rows:
                    continue
                if cell.value:
                    cell.border = border_
                    cell.alignment = align_
                    max_len = max(max_len, len(str(cell.value)))
            ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 2, 60)

    # Sheet 1: Resumen
    ws1 = wb.active
    ws1.title = 'Resumen'
    _setup_sheet_header(ws1, 'Reporte de Auditoria - Organizacion', period_sub, col_span=2)
    ws1_header_row = ws1.max_row + 1
    all_findings = []
    for s in scans:
        all_findings.extend(s.findings.all())
    stats = {
        'total': len(all_findings),
        'critical': sum(1 for f in all_findings if f.severity == 'CRITICAL'),
        'high': sum(1 for f in all_findings if f.severity == 'HIGH'),
        'medium': sum(1 for f in all_findings if f.severity == 'MEDIUM'),
        'low': sum(1 for f in all_findings if f.severity == 'LOW'),
        'info': sum(1 for f in all_findings if f.severity == 'INFO'),
    }
    rows = [
        ['Organizacion', org_name],
        ['Periodo Inicio', start_str],
        ['Periodo Fin', end_str],
        ['Escaneos Incluidos', len(scans)],
        ['Total Hallazgos', stats['total']],
        ['Criticos', stats['critical']],
        ['Altos', stats['high']],
        ['Medios', stats['medium']],
        ['Bajos', stats['low']],
        ['Info', stats['info']],
    ]
    ws1.append(['Campo', 'Valor'])
    for c in ws1[ws1_header_row]:
        c.font = header_font
        c.fill = header_fill
        c.border = border
    for r in rows:
        ws1.append(r)
    _auto_width(ws1, skip_rows=1)
    _finalize_table_sheet(ws1, ws1_header_row, tab_color='2563EB', zebra=True)

    # Sheet 2: Escaneos
    ws2 = wb.create_sheet('Escaneos')
    headers = ['Scan ID', 'URL', 'Fecha Inicio', 'Estado', 'Hallazgos']
    _setup_sheet_header(ws2, 'Escaneos Incluidos', period_sub, col_span=len(headers))
    ws2_header_row = ws2.max_row + 1
    ws2.append(headers)
    for c in ws2[ws2_header_row]:
        c.font = header_font
        c.fill = header_fill
        c.border = border
    for s in scans:
        ws2.append([
            s.pk,
            s.url_asset.url if s.url_asset else '',
            s.started_at.strftime('%Y-%m-%d %H:%M:%S'),
            s.status,
            s.findings.count(),
        ])
    _auto_width(ws2, skip_rows=1)
    _finalize_table_sheet(ws2, ws2_header_row, tab_color='0891B2', zebra=True)

    # Sheet 3: Hallazgos
    ws3 = wb.create_sheet('Hallazgos')
    headers = [
        'Scan ID', 'URL', 'Fecha Escaneo', 'Severidad',
        'Categoria', 'Titulo', 'Descripcion', 'Recomendacion',
    ]
    _setup_sheet_header(ws3, 'Hallazgos Tecnicos', period_sub, col_span=len(headers))
    ws3_header_row = ws3.max_row + 1
    ws3.append(headers)
    for c in ws3[ws3_header_row]:
        c.font = header_font
        c.fill = header_fill
        c.border = border
    severity_fills = {
        'CRITICAL': PatternFill(start_color='FFEDE9FE', end_color='FFEDE9FE', fill_type='solid'),
        'HIGH': PatternFill(start_color='FFFEE2E2', end_color='FFFEE2E2', fill_type='solid'),
        'MEDIUM': PatternFill(start_color='FFFEF3C7', end_color='FFFEF3C7', fill_type='solid'),
        'LOW': PatternFill(start_color='FFDBEAFE', end_color='FFDBEAFE', fill_type='solid'),
    }
    for s in scans:
        url = s.url_asset.url if s.url_asset else ''
        date_str = s.started_at.strftime('%Y-%m-%d %H:%M:%S')
        for f in s.findings.all():
            ws3.append([
                s.pk, url, date_str, f.severity, f.category,
                f.title, f.description, f.recommendation,
            ])
            sev_fill = severity_fills.get((f.severity or '').upper())
            if sev_fill:
                ws3.cell(row=ws3.max_row, column=4).fill = sev_fill
    _auto_width(ws3, skip_rows=1)
    _finalize_table_sheet(ws3, ws3_header_row, tab_color='DC2626', zebra=False)

    buffer = BytesIO()
    wb.save(buffer)
    buffer.seek(0)
    return buffer


def _safe_filename_part(text):
    """Slugify arbitrary text for use in a Content-Disposition filename."""
    keep = [c if (c.isalnum() or c in ('-', '_')) else '_' for c in text.strip()]
    return ''.join(keep)[:60] or 'sitio'


def _build_org_report_file_response(scans, fmt, org_name, start_str, end_str, scope_label=None):
    """Build an HTTP response with the org-level (or single-URL) report file."""
    name_suffix = f'_{_safe_filename_part(scope_label)}' if scope_label else ''

    if fmt == 'pdf':
        if not REPORTLAB_AVAILABLE:
            return Response(
                {'detail': 'ReportLab no disponible para generar PDF.'},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )
        buffer = _build_org_pdf_reportlab(scans, org_name, start_str, end_str, scope_label)
        resp = HttpResponse(buffer.getvalue(), content_type='application/pdf')
        safe_name = org_name.replace(' ', '_')
        resp['Content-Disposition'] = (
            f'attachment; filename="reporte_org_{safe_name}{name_suffix}_{start_str}_{end_str}.pdf"'
        )
        return resp

    if fmt in ('excel', 'xlsx'):
        buffer = _build_org_excel(scans, org_name, start_str, end_str, scope_label)
        resp = HttpResponse(
            buffer.getvalue(),
            content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        )
        safe_name = org_name.replace(' ', '_')
        resp['Content-Disposition'] = (
            f'attachment; filename="reporte_org_{safe_name}{name_suffix}_{start_str}_{end_str}.xlsx"'
        )
        return resp

    return Response(
        {'detail': f'Formato no soportado: {fmt}.'},
        status=status.HTTP_400_BAD_REQUEST,
    )


@api_view(['GET'])
@permission_classes([permissions.IsAuthenticated])
def org_report(request):
    """Generate an organization-level report for a date range.

    Query params:
        start: YYYY-MM-DD (required)
        end:   YYYY-MM-DD (required)
        format: pdf | excel | xlsx (default: pdf)
        url_asset_id: optional — scope the report to a single registered URL
                      instead of the whole organization.
    """
    org = request.user.organization
    if not org:
        return Response(
            {'detail': 'No perteneces a ninguna organizacion.'},
            status=status.HTTP_400_BAD_REQUEST,
        )

    start_str = request.query_params.get('start')
    end_str = request.query_params.get('end')
    if not start_str or not end_str:
        return Response(
            {'detail': 'Parametros start y end son requeridos (YYYY-MM-DD).'},
            status=status.HTTP_400_BAD_REQUEST,
        )

    from datetime import date as _date
    try:
        start_d = _date.fromisoformat(start_str)
        end_d = _date.fromisoformat(end_str)
    except ValueError:
        return Response(
            {'detail': 'Formato de fecha invalido. Use YYYY-MM-DD.'},
            status=status.HTTP_400_BAD_REQUEST,
        )

    if start_d > end_d:
        return Response(
            {'detail': 'La fecha de inicio no puede ser mayor que la fecha de fin.'},
            status=status.HTTP_422_UNPROCESSABLE_ENTITY,
        )

    scope_label = None
    url_asset_id = request.query_params.get('url_asset_id')
    scans_qs = Scan.objects.filter(
        url_asset__organization_id=org.id,
        started_at__date__gte=start_d,
        started_at__date__lte=end_d,
    )
    if url_asset_id:
        try:
            url_asset = URLAsset.objects.get(pk=url_asset_id, organization_id=org.id)
        except (URLAsset.DoesNotExist, ValueError):
            return Response(
                {'detail': 'URL no encontrada o no pertenece a tu organizacion.'},
                status=status.HTTP_404_NOT_FOUND,
            )
        scans_qs = scans_qs.filter(url_asset_id=url_asset.pk)
        scope_label = url_asset.name or url_asset.url

    scans = scans_qs.select_related('url_asset').prefetch_related('findings').order_by('-started_at')

    if not scans.exists():
        return Response(
            {'detail': 'Sin actividad de escaneo en el rango seleccionado.'},
            status=status.HTTP_422_UNPROCESSABLE_ENTITY,
        )

    fmt = (request.query_params.get('format') or 'pdf').lower()
    return _build_org_report_file_response(scans, fmt, org.name, start_str, end_str, scope_label)
